name: Actualizar Dashboard de Trading
on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch:      # Botón para ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar Extracción
        env:
          MYFXBOOK_EMAIL: ${{ secrets.MYFXBOOK_EMAIL }}
          MYFXBOOK_PASSWORD: ${{ secrets.MYFXBOOK_PASSWORD }}
        run: python update_data.py
      - name: Guardar Cambios en el Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add datos_trading.json
          git commit -m "Actualización automática de datos" || exit 0
          git push
