name: Update Trading Data

on:
  schedule:
    # Los 5 asteriscos significan "cada minuto de cada hora de cada día"
    - cron: '* * * * *'
  
  # Este comando extra te agrega un botón en GitHub para ejecutarlo manualmente cuando quieras
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar Extracción
        env:
          MYFXBOOK_EMAIL: ${{ secrets.MYFXBOOK_EMAIL }}
          MYFXBOOK_PASSWORD: ${{ secrets.MYFXBOOK_PASSWORD }}
        run: python update_data.py
      - name: Guardar Cambios en el Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add datos_trading.json
          git commit -m "Actualización automática de datos" || exit 0
          git push
